import 'package:udm_alias_app/word_entity.dart';

List<WordEntity> easyWords = [
  WordEntity('Адями', 'человек'),
  WordEntity('Анай', 'мама'),
  WordEntity('Ангес', 'подбородок'),
  WordEntity('Ар', 'год'),
  WordEntity('Арама', 'роща'),
  WordEntity('Арбери', 'вещь'),
  WordEntity('Арганчи', 'гармонист'),
  WordEntity('Арня', 'неделя'),
  WordEntity('Арымтурын', 'полынь'),
  WordEntity('Атай', 'отец'),
  WordEntity('Атас', 'петух'),
  WordEntity('Бака', 'лягушка'),
  WordEntity('Бакча', 'огород'),
  WordEntity('Бам', 'щека'),
  WordEntity('Бамал', 'склон горы'),
  WordEntity('Басма', 'ткань'),
  WordEntity('Батыр', 'богатырь'),
  WordEntity('Бекче', 'бочка'),
  WordEntity('Берпал', 'зад'),
  WordEntity('Бирӟы', 'пуговица'),
  WordEntity('Боды', 'палка'),
  WordEntity('Борддор', 'стена'),
  WordEntity('Боры', 'клубника'),
  WordEntity('Бубыли', 'бабочка'),
  WordEntity('Бугор', 'клубок'),
  WordEntity('Будос', 'растение'),
  WordEntity('Буёл', 'краска'),
  WordEntity('Бус', 'туман'),
  WordEntity('Бусы', 'поле'),
  WordEntity('Бутник', 'мята'),
  WordEntity('Быж', 'хвост'),
  WordEntity('Бычкы', 'пила'),
  WordEntity('Вай', 'ветка'),
  WordEntity('Вал', 'лошадь'),
  WordEntity('Валан', 'понимание'),
  WordEntity('Валес', 'кровать'),
  WordEntity('Вамыш', 'шаг'),
  WordEntity('Вандэт', 'отрез, кусок'),
  WordEntity('Ватсэт', 'приложение'),
  WordEntity('Ведӥн', 'ведьма'),
  WordEntity('Вень', 'игла'),
  WordEntity('Верос', 'рассказ'),
  WordEntity('Визь-кенеш', 'совет'),
  WordEntity('Викышъям', 'всхлипывание'),
  WordEntity('Вир', 'кровь'),
  WordEntity('Вирнунал', 'среда'),
  WordEntity('Вирсэр', 'вена'),
  WordEntity('Виртырем', 'кровяная колбаса'),
  WordEntity('Вис', 'щель'),
  WordEntity('Висён', 'болезнь'),
  WordEntity('Висъет', 'комната'),
  WordEntity('Вӧёгуби', 'маслята'),
  WordEntity('Вожнуны', 'младенец'),
  WordEntity('Возь', 'лужайка'),
  WordEntity('Вӧй', 'масло'),
  WordEntity('Вӧлдэт', 'потолок'),
  WordEntity('Вормись', 'победитель'),
  WordEntity('Вотэс', 'сеть'),
  WordEntity('Вӧш', 'кухонная доска'),
  WordEntity('Ву', 'вода'),
  WordEntity('Вужер', 'тень'),
  WordEntity('Вукарнан', 'стрекоза'),
  WordEntity('Вуюись', 'радуга'),
  WordEntity('Выж', 'мост'),
  WordEntity('Выжы', 'корень'),
  WordEntity('Выжыкыл', 'сказка'),
  WordEntity('Гадь', 'грудь'),
  WordEntity('Гажан', 'уважение'),
  WordEntity('Геры', 'плуг'),
  WordEntity('Гид', 'хлев'),
  WordEntity('Гижы', 'ноготь'),
  WordEntity('Гогы', 'пупок'),
  WordEntity('Гож', 'линия'),
  WordEntity('Гожтэт', 'письмо'),
  WordEntity('Гон', 'шерсть, пух, волосы на теле'),
  WordEntity('Гондыр', 'медведь'),
  WordEntity('Гоп', 'яма'),
  WordEntity('Гордсюй', 'глина'),
  WordEntity('Губи', 'грибы'),
  WordEntity('Гудыри', 'гром'),
  WordEntity('Гуждор', 'травка, лужайка'),
  WordEntity('Гур', 'печь'),
  WordEntity('Гынсапег', 'валенки'),
  WordEntity('Гырлы', 'колокол'),
  WordEntity('Даур', 'век'),
  WordEntity('Дӥськут', 'одежда'),
  WordEntity('Дӧдьы', 'санки'),
  WordEntity('Дор', 'дом'),
  WordEntity('Дугдылонни', 'остановка'),
  WordEntity('Дукес', 'камзол'),
  WordEntity('Дукъя', 'глухарь'),
  WordEntity('Дун', 'цена'),
  WordEntity('Дунне', 'мир'),
  WordEntity('Душес', 'орел'),
  WordEntity('Дуэ', 'верблюд'),
  WordEntity('Дыдык', 'голубь'),
  WordEntity('Дыльды', 'слюна'),
  WordEntity('Дыр', 'время'),
  WordEntity('Дышетӥсь', 'учитель'),
  WordEntity('Дышетскон', 'учеба'),
  WordEntity('Дэрем', 'платье'),
  WordEntity('Дэри', 'грязь'),
  WordEntity('Дядяй', 'брат'),
  WordEntity('Егитлык', 'молодость'),
  WordEntity('Ез', 'провод'),
  WordEntity('Емыш', 'плод'),
  WordEntity('Ёрос', 'район'),
  WordEntity('Етӥн', 'лён'),
  WordEntity('Жаг', 'мусор'),
  WordEntity('Жильы', 'цепь'),
  WordEntity('Жингыртон', 'звонок'),
  WordEntity('Ӝӧк', 'стол'),
  WordEntity('Ӝӧккышет', 'скатерть'),
  WordEntity('Ӝуйы', 'мох'),
  WordEntity('Ӝук', 'каша'),
  WordEntity('Ӝыт', 'вечер'),
  WordEntity('Зангари', 'василек'),
  WordEntity('Зарезь', 'море'),
  WordEntity('Зарни', 'золото'),
  WordEntity('Ӟольгыри', 'воробей'),
  WordEntity('Зор', 'дождь'),
  WordEntity('Зундэс', 'кольцо'),
  WordEntity('Зын', 'запах, вонь'),
  WordEntity('Инбам', 'небо'),
  WordEntity('Инсьӧр', 'космос'),
  WordEntity('Йӧ', 'лёд'),
  WordEntity('Карнан', 'коромысло'),
  WordEntity('Качы', 'ножницы'),
  WordEntity('Кизили', 'звезда'),
  WordEntity('Кион', 'волк'),
  WordEntity('Комак', 'крыса'),
  WordEntity('Корка', 'дом'),
  WordEntity('Коӵыш', 'кошка'),
  WordEntity('Куалялюльы', 'улитка'),
  WordEntity('Куара', 'голос'),
  WordEntity('Курег', 'курица'),
  WordEntity('Курка', 'индюк'),
  WordEntity('Кый', 'змея'),
  WordEntity('Кылбур', 'стихотворение'),
  WordEntity('Кырӟась', 'певец'),
  WordEntity('Кышет', 'платок'),
  WordEntity('Кышно', 'жена'),
  WordEntity('Лапас', 'навес, сарай'),
  WordEntity('Липет', 'крыша'),
  WordEntity('Лымы', 'снег'),
  WordEntity('Мамык', 'вата'),
  WordEntity('Мыйык', 'усы'),
  WordEntity('Нылпи', 'ребенок'),
  WordEntity('Ныпъет', 'заплечная люлька'),
  WordEntity('Нюлэс', 'лес'),
  WordEntity('Нянь', 'хлеб'),
  WordEntity('Омыр', 'воздух'),
  WordEntity('Ӧс', 'дверь'),
  WordEntity('Оскон', 'вера'),
  WordEntity('Пелепон', 'телефон'),
  WordEntity('Пельнянь', 'пельмень'),
  WordEntity('Пилем', 'облако'),
  WordEntity('Писпу', 'дерево'),
  WordEntity('Писэйпи', 'котенок'),
  WordEntity('Питыран', 'колесо'),
  WordEntity('Пӧзьы', 'варежка'),
  WordEntity('Пукон', 'стул'),
  WordEntity('Пумиськон', 'встреча'),
  WordEntity('Пуны', 'собака'),
  WordEntity('Пуны', 'собака'),
  WordEntity('Пуньы', 'ложка'),
  WordEntity('Пуньы', 'ложка'),
  WordEntity('Пыдкутчан', 'обувь'),
  WordEntity('Сизь', 'дятел'),
  WordEntity('Сӥзьыл', 'осень'),
  WordEntity('Скал', 'корова'),
  WordEntity('Сэрег', 'угол'),
  WordEntity('Сюлэм', 'сердце'),
  WordEntity('Сюрес', 'дорога'),
  WordEntity('Толэзь', 'месяц'),
  WordEntity('Тубат', 'лестница'),
  WordEntity('Турын', 'трава'),
  WordEntity('Туспуктӥсь', 'фотограф'),
  WordEntity('Ты', 'озеро'),
  WordEntity('Тылобурдо', 'птица'),
  WordEntity('Уйвӧт', 'сон'),
  WordEntity('Укно', 'окно'),
  WordEntity('Уробо', 'тележка'),
  WordEntity('Усьтон', 'ключ'),
  WordEntity('Уӵы', 'соловей'),
  WordEntity('Чибинь', 'комар'),
  WordEntity('Чилектэм', 'молния'),
  WordEntity('Чорыг', 'рыба'),
  WordEntity('Чукиндэр', 'свекла'),
  WordEntity('Чулкапыд', 'носки'),
  WordEntity('Ӵушъял', 'ёжик'),
  WordEntity('Ӵыжы-выжы', 'родня'),
  WordEntity('Ӵын', 'дым'),
  WordEntity('Шумпотон', 'радость'),
  WordEntity('Шунды', 'солнце'),
  WordEntity('Шур', 'река'),
  WordEntity('Шыд', 'суп'),
  WordEntity('Шырпи', 'мышонок'),
  WordEntity('Ымныр', 'лицо'),
  WordEntity('Эксэй', 'король'),
  WordEntity('Эшъёс', 'друзья'),
  WordEntity('Юмшан', 'гуляния'),
  WordEntity('Яратон', 'любовь'),
];

List<WordEntity> mediumWords = [
  WordEntity('Абдран', 'шок, удивление'),
  WordEntity('Адӟон', 'судьба'),
  WordEntity('Адямилык', 'человечность'),
  WordEntity('Азвесь', 'серебро'),
  WordEntity('Азинлык', 'успех'),
  WordEntity('Азьдага', 'крокодил'),
  WordEntity('Азьпинь', 'резец'),
  WordEntity('Азьтэмьяськон', 'лень'),
  WordEntity('Айкай', 'ой ли (зачин песни), игрище'),
  WordEntity('Акашка', 'Пасха'),
  WordEntity('Алангасар', 'великан, мифологическое существо'),
  WordEntity('Алдаськон', 'ложь'),
  WordEntity('Амал', 'способ'),
  WordEntity('Ана', 'полоса (пахотной земли)'),
  WordEntity('Андан', 'сталь'),
  WordEntity('Апай', 'сестра'),
  WordEntity('Аран', 'жатва'),
  WordEntity('Арес', 'возраст'),
  WordEntity('Артана', 'поленница'),
  WordEntity('Аслобет', 'самолет'),
  WordEntity('Асшӧдон', 'самосознание'),
  WordEntity('Ашальчи', 'зубровка'),
  WordEntity('Бабыли', 'кудри'),
  WordEntity('Бадьпу', 'ива'),
  WordEntity('Бадяр', 'клен'),
  WordEntity('Байлык', 'богатство'),
  WordEntity('Балянпи', 'рысёнок'),
  WordEntity('Бамкышет', 'полотенце'),
  WordEntity('Бамчультро', 'скулы'),
  WordEntity('Барангы', 'картошка'),
  WordEntity('Басьяськись', 'покупатель'),
  WordEntity('Батырлык', 'храбрость'),
  WordEntity('Бервыл', 'остаток'),
  WordEntity('Берган', 'вращение, кружение'),
  WordEntity('Берпумкыл', 'послесловие, эпилог'),
  WordEntity('Берпумъян', 'завершение'),
  WordEntity('Бискыли', 'круглый хлеб из яровой муки'),
  WordEntity('Бичпотон', 'щекотка'),
  WordEntity('Бӧксон', 'мычание'),
  WordEntity('Бӧрдон', 'плач'),
  WordEntity('Борыпуд', 'кустик клубники'),
  WordEntity('Борыян', 'сбор клубники'),
  WordEntity('Бӧчы', 'жук'),
  WordEntity('Будэтон', 'выращивание'),
  WordEntity('Буйган', 'успокоение'),
  WordEntity('Бурд', 'крыло'),
  WordEntity('Бурдъяськон', 'окрыление'),
  WordEntity('Бутьмар', 'перевязь, женское украшение с нашитыми монетами'),
  WordEntity('Быгатонлык', 'умение'),
  WordEntity('Быгытъёс', 'мышцы'),
  WordEntity('Ваёбыж', 'ласточка'),
  WordEntity('Вакыт', 'время, пора'),
  WordEntity('Валан', 'понимание'),
  WordEntity('Валатон', 'понятие'),
  WordEntity('Валэктон', 'ответ'),
  WordEntity('Ваньбур', 'ресурс'),
  WordEntity('Варманай', 'теща'),
  WordEntity('Варматай', 'тесть'),
  WordEntity('Ви', 'момент'),
  WordEntity('Визь', 'ум'),
  WordEntity('Визьбур', 'разум'),
  WordEntity('Визькыл', 'пословица'),
  WordEntity('Визьнодан', 'воспитание'),
  WordEntity('Визьсынан', 'головоломка'),
  WordEntity('Виртурын', 'зверобой'),
  WordEntity('Вожвылъяськон', 'соревнование'),
  WordEntity('Вожмаськон', 'конкурс, конкурирование'),
  WordEntity('Вожпотон', 'злость'),
  WordEntity('Возьдаськон', 'застенчивость'),
  WordEntity('Ворсэт', 'крышка'),
  WordEntity('Вӧсяськон', 'моление'),
  WordEntity('Вӧт', 'сон'),
  WordEntity('Вурыс', 'шов'),
  WordEntity('Вучайы', 'норка, бобр'),
  WordEntity('Вырйыл', 'вершина'),
  WordEntity('Вышкы', 'кадка, кадушка'),
  WordEntity('Газетчи', 'корреспондент, журналист'),
  WordEntity('Герӟет', 'подвязка'),
  WordEntity('Гожпус', 'буква'),
  WordEntity('Гоносутэр', 'крыжовник'),
  WordEntity('Гудырикошкон', 'август'),
  WordEntity('Данлык', 'слава'),
  WordEntity('Дасьлык', 'готовность'),
  WordEntity('Дӥсьтон', 'решительность'),
  WordEntity('Думет', 'привязь'),
  WordEntity('Дуринчи', 'оса'),
  WordEntity('Дуры', 'черпак'),
  WordEntity('Дымбыр', 'барабан'),
  WordEntity('Дырпус', 'календарь'),
  WordEntity('Е', 'ремень'),
  WordEntity('Ёзви', 'сустав'),
  WordEntity('Ёрмон', 'нужда'),
  WordEntity('Ӝегатон', 'задержка'),
  WordEntity('Ӝожомон', 'грусть'),
  WordEntity('Ӝожон', 'толокно'),
  WordEntity('Ӝомал', 'сумерки'),
  WordEntity('Зӧктала', 'толщина'),
  WordEntity('Зыр', 'дубина'),
  WordEntity('Зэмлык', 'правда'),
  WordEntity('Инвис', 'горизонт'),
  WordEntity('Йӧкана', 'холодильник'),
  WordEntity('Куркуян', 'свалка'),
  WordEntity('Пыж', 'лодка'),
  WordEntity('Суйпоскес', 'браслет'),
  WordEntity('Сюлэмшугъяськон', 'переживание'),
  WordEntity('Тазалык', 'здоровье'),
  WordEntity('Тӧлпери', 'вихрь, смерч'),
  WordEntity('Тусь', 'корыто'),
  WordEntity('Ужпум', 'цель'),
  WordEntity('Уллапал', 'низовье, нижняя часть улицы'),
  WordEntity('Шормуӵ', 'остров'),
  WordEntity('Шырпу', 'заноза'),
];

List<WordEntity> hardWords = [
  WordEntity('Азькыл', 'предисловие, пролог'),
  WordEntity('Айшон', 'головной убор замужней удмуртки'),
  WordEntity('Акач-тукач', 'улитка'),
  WordEntity('Акрокылбур', 'акростих'),
  WordEntity('Алданчи', 'обманщик'),
  WordEntity('Арлан', 'хомяк'),
  WordEntity('Арыкман', 'репей'),
  WordEntity('Арыслан', 'лев'),
  WordEntity('Аспӧртэмлык', 'особенность'),
  WordEntity('Асэстон', 'присвоение'),
  WordEntity('Бакель', 'благословение'),
  WordEntity('Беренэс', 'попугай'),
  WordEntity('Бӧдёно', 'перепел'),
  WordEntity('Бӧляк', 'родня'),
  WordEntity('Бӧрысьёс', 'гости со стороны невесты'),
  WordEntity('Буко', 'дуга в упряжке'),
  WordEntity('Бункур', 'липовая кора'),
  WordEntity('Бургы', 'кадка, кадушка'),
  WordEntity('Вайыж', 'оглобля'),
  WordEntity('Ваментул', 'упрямец'),
  WordEntity('Вапум', 'время'),
  WordEntity('Веме', 'общая помощь, помочи'),
  WordEntity('Вераськон', 'разговор'),
  WordEntity('Веттэт', 'соус'),
  WordEntity('Визян', 'пост'),
  WordEntity('Вогыри', 'рябь'),
  WordEntity('Возёс', 'хозяйство'),
  WordEntity('Выллапал', 'верхняя часть улицы'),
  WordEntity('Дарт', 'азарт, задор'),
  WordEntity('Дэймон', 'ужас, испуг'),
  WordEntity('Дэлет', 'польза, благополучие'),
  WordEntity('Дэра', 'холст'),
  WordEntity('Ёзэт', 'отдел, отделение'),
  WordEntity('Ерпечка', 'непоседа'),
  WordEntity('Жадён', 'усталость'),
  WordEntity('Ӝажы', 'полка'),
  WordEntity('Ӝоглык', 'скорость'),
  WordEntity('Жугиськон', 'драка'),
  WordEntity('Ӟаныкай', 'милая'),
  WordEntity('Заринча', 'зарница'),
  WordEntity('Зӥбет', 'гнёт'),
  WordEntity('Зоргуби', 'дождевик'),
  WordEntity('Зуркан', 'тряска'),
  WordEntity('Зурод', 'стог'),
  WordEntity('Зынпесьтэр', 'полевой клоп'),
  WordEntity('Зэрпал', 'Алангасар (великан, мифологическое существо)'),
  WordEntity('Катанчи', 'занавес'),
  WordEntity('Кивалтӥсь', 'руководитель'),
  WordEntity('Ляльчи', 'раб'),
  WordEntity('Омырвӧт', 'иллюзия'),
  WordEntity('Пыль', 'слон'),
  WordEntity('Ташбака', 'черепаха'),
  WordEntity('Тэльбуго', 'вожжи'),
];

List<String> hardestWords = [
  'пукон',
  'ӝӧк',
  'пуньы',
  'писпу',
  'укно',
  'пуны',
  'ӝук',
  'шыд',
];
